# Generated by Django 5.1.2 on 2024-11-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can edit an exiting book'), ('can_delete_book', 'Can delete a book')]},
        ),
    ]
